--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 6.5.16.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 12/08/2023 7:31:58 pm
-- Server version: 16.00.4045
--


SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO
USE master
GO

IF DB_NAME() <> N'master' SET NOEXEC ON

--
-- Create database [Bookstore]
--
PRINT (N'Create database [Bookstore]')
GO
CREATE DATABASE Bookstore
ON PRIMARY(
    NAME = N'Bookstore',
    FILENAME = N'/var/opt/mssql/data/Bookstore.mdf',
    SIZE = 10240KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 1024KB
)
LOG ON(
    NAME = N'Bookstore_log',
    FILENAME = N'/var/opt/mssql/data/Bookstore_log.ldf',
    SIZE = 5120KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10%
)
GO

--
-- Alter database
--
PRINT (N'Alter database')
GO
ALTER DATABASE Bookstore
  SET
    ANSI_NULL_DEFAULT OFF,
    ANSI_NULLS OFF,
    ANSI_PADDING OFF,
    ANSI_WARNINGS OFF,
    ARITHABORT OFF,
    AUTO_CLOSE OFF,
    AUTO_CREATE_STATISTICS ON,
    AUTO_SHRINK OFF,
    AUTO_UPDATE_STATISTICS ON,
    AUTO_UPDATE_STATISTICS_ASYNC OFF,
    COMPATIBILITY_LEVEL = 160,
    CONCAT_NULL_YIELDS_NULL OFF,
    CURSOR_CLOSE_ON_COMMIT OFF,
    CURSOR_DEFAULT GLOBAL,
    DATE_CORRELATION_OPTIMIZATION OFF,
    DB_CHAINING OFF,
    HONOR_BROKER_PRIORITY OFF,
    MULTI_USER,
    NUMERIC_ROUNDABORT OFF,
    PAGE_VERIFY CHECKSUM,
    PARAMETERIZATION SIMPLE,
    QUOTED_IDENTIFIER OFF,
    READ_COMMITTED_SNAPSHOT OFF,
    RECOVERY FULL,
    RECURSIVE_TRIGGERS OFF,
    TRANSFORM_NOISE_WORDS = OFF,
    TRUSTWORTHY OFF
    WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE Bookstore
  SET DISABLE_BROKER
GO

ALTER DATABASE Bookstore
  SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

EXECUTE sp_configure 'show advanced options', 1;
GO
RECONFIGURE;
GO
EXECUTE sp_configure 'nested triggers', 1;
GO
RECONFIGURE;
GO

ALTER DATABASE Bookstore
  SET QUERY_STORE = OFF
GO

USE Bookstore
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE Bookstore
GO

IF DB_NAME() <> N'Bookstore' SET NOEXEC ON
GO

--
-- Create table [dbo].[Users]
--
PRINT (N'Create table [dbo].[Users]')
GO
CREATE TABLE dbo.Users (
  Id int IDENTITY,
  Username nvarchar(max) NOT NULL,
  Email nvarchar(max) NOT NULL,
  Password nvarchar(max) NOT NULL,
  CONSTRAINT PK_Users PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[Books]
--
PRINT (N'Create table [dbo].[Books]')
GO
CREATE TABLE dbo.Books (
  Id int IDENTITY,
  Title nvarchar(max) NOT NULL,
  Author nvarchar(max) NOT NULL,
  PublicationYear nvarchar(max) NOT NULL,
  Isbn nvarchar(max) NOT NULL,
  CONSTRAINT PK_Books PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[__EFMigrationsHistory]
--
PRINT (N'Create table [dbo].[__EFMigrationsHistory]')
GO
CREATE TABLE dbo.__EFMigrationsHistory (
  MigrationId nvarchar(150) NOT NULL,
  ProductVersion nvarchar(32) NOT NULL,
  CONSTRAINT PK___EFMigrationsHistory PRIMARY KEY CLUSTERED (MigrationId)
)
ON [PRIMARY]
GO

-- 
-- Dumping data for table __EFMigrationsHistory
--
PRINT (N'Dumping data for table __EFMigrationsHistory')
INSERT dbo.__EFMigrationsHistory VALUES (N'20230805115921_InitialCreate', N'7.0.9')
INSERT dbo.__EFMigrationsHistory VALUES (N'20230805122337_InitialCreate', N'7.0.9')
GO

-- 
-- Dumping data for table Users
--
PRINT (N'Dumping data for table Users')
SET IDENTITY_INSERT dbo.Users ON
GO
INSERT dbo.Users(Id, Username, Email, Password) VALUES (2, N'Alexis', N'some@randomdomain.com', N'Qhx213Vjr6GRSEawEL0WTzlb00whAuXpngy5zxc8HYc=')
INSERT dbo.Users(Id, Username, Email, Password) VALUES (3, N'TestUser', N'test@random', N'JBP7NwmwWTnwTPLpL30Il/wllvmtC4qeqFXHv+uq6JI=')
INSERT dbo.Users(Id, Username, Email, Password) VALUES (4, N'IntegrationTest', N'some@email', N'uclQZA4bN0DpisuT5mnGV2b2Zw3RYJupH/QQUrpIxvM=')
GO
SET IDENTITY_INSERT dbo.Users OFF
GO

-- 
-- Dumping data for table Books
--
PRINT (N'Dumping data for table Books')
SET IDENTITY_INSERT dbo.Books ON
GO
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (2, N'Harry Potter and the Philosopher''s Stone', N'J. K. Rowling', N'1997', N'0-061-96436-0')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (3, N'The Great Gatsby', N'F. Scott Fitzgerald', N'1925', N'9780743273565')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (4, N'To Kill a Mockingbird', N'Harper Lee', N'1960', N'0061120081')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (5, N'1984', N'George Orwell', N'1949', N'9780451524935')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (6, N'Pride and Prejudice', N'Jane Austen', N'1813', N'9780486284736')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (7, N'The Lord of the Rings', N'J.R.R. Tolkien', N'1954', N'9780618640157')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (8, N'Brave New World', N'Aldous Huxley', N'1932', N'9780060850524')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (11, N'The Hobbit', N'J.R.R. Tolkien', N'1937', N'9780618260300')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (12, N'One Hundred Years of Solitude', N'Gabriel Garcia Marquez', N'1967', N'9780060883287')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (13, N'Moby-Dick', N'Herman Melville', N'1851', N'9780142000083')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (14, N'The Secret Garden', N'Frances Hodgson Burnett', N'1911', N'978-0143106456')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (15, N'The Catcher in the Rye', N'J.D. Salinger', N'1951', N'978-0316769488')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (16, N'Jane Eyre', N'Charlotte Bronte', N'1847', N'978-0141441146')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (17, N'The Adventures of Huckleberry Finn', N'Mark Twain', N'1884', N'978-0486280615')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (18, N'Wuthering Heights', N'Emily Bronte', N'1847', N'978-0141439556')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (19, N'The Picture of Dorian Gray', N'Oscar Wilde', N'1890', N'978-0141439570')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (20, N'Alice''s Adventures in Wonderland', N'Lewis Carroll', N'1865', N'978-1503290327')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (21, N'Lord of the Flies', N'William Golding', N'1954', N'978-0571295715')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (22, N'Fahrenheit 451', N'Ray Bradbury', N'1953', N'978-1451673319')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (23, N'The Chronicles of Narnia', N'C.S. Lewis', N'1950', N'978-0064404990')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (24, N'Dracula', N'Bram Stoker', N'1897', N'978-0486411095')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (25, N'The Adventures of Sherlock Holmes', N'Arthur Conan Doyle', N'1892', N'978-0553212419')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (26, N'The War of the Worlds', N'H.G. Wells', N'1898', N'978-1503295926')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (27, N'Frankenstein', N'Mary Shelley', N'1818', N'978-0486282114')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (28, N'The Alchemist', N'Paulo Coelho', N'1988', N'978-0061122415')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (29, N'The Odyssey', N'Homer', N'-800', N'978-0140268867')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (30, N'Great Expectations', N'Charles Dickens', N'1861', N'978-0141439563')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (31, N'The Shining', N'Stephen King', N'1977', N'978-0307743657')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (32, N'Catch-22', N'Joseph Heller', N'1961', N'978-1451626650')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (33, N'A Tale of Two Cities', N'Charles Dickens', N'1859', N'978-0486417769')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (34, N'Pride and Prejudice and Zombies', N'Seth Grahame-Smith', N'2009', N'978-1594743344')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (35, N'The Hunger Games', N'Suzanne Collins', N'2008', N'978-0439023528')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (36, N'The Da Vinci Code', N'Dan Brown', N'2003', N'978-0307474278')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (37, N'The Road', N'Cormac McCarthy', N'2006', N'978-0307387899')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (38, N'The Lovely Bones', N'Alice Sebold', N'2002', N'978-0316666343')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (39, N'The Color Purple', N'Alice Walker', N'1982', N'978-0156031820')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (40, N'The Kite Runner', N'Khaled Hosseini', N'2003', N'978-1594631931')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (41, N'The Sun Also Rises', N'Ernest Hemingway', N'1926', N'978-0743297332')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (42, N'A Clockwork Orange', N'Anthony Burgess', N'1962', N'978-0393312836')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (43, N'Gone with the Wind', N'Margaret Mitchell', N'1936', N'978-1451635621')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (44, N'The Grapes of Wrath', N'John Steinbeck', N'1939', N'978-0143039433')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (45, N'The Outsiders', N'S.E. Hinton', N'1967', N'978-0140385724')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (46, N'The Fault in Our Stars', N'John Green', N'2012', N'978-0142424179')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (47, N'The Handmaid''s Tale', N'Margaret Atwood', N'1985', N'978-0385490818')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (48, N'The Old Man and the Sea', N'Ernest Hemingway', N'1952', N'978-0684801223')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (49, N'The Bell Jar', N'Sylvia Plath', N'1963', N'978-0061148514')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (50, N'Watership Down', N'Richard Adams', N'1972', N'978-0743277709')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (51, N'The Hitchhiker''s Guide to the Galaxy', N'Douglas Adams', N'1979', N'978-0345391803')
INSERT dbo.Books(Id, Title, Author, PublicationYear, Isbn) VALUES (54, N'TestBook - Testing Update Functionality', N'IntegrationTest-2', N'2023', N'TEST-2023-integration')
GO
SET IDENTITY_INSERT dbo.Books OFF
GO
SET NOEXEC OFF
GO